name: Self-hosted Build & Push Docker Image to container image registry

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:
  docker:
    uses: clytage/workflows/.github/workflows/docker-self-hosted-build.yml@main
    secrets: inherit